title: "Distributed Systems"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
